name: Nodepp C++ Cross-Platform CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_and_test:

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            compiler: g++
          - os: macos-latest
            compiler: g++
          - os: windows-latest
            compiler: mingw
          - os: windows-latest
            compiler: msvc

    runs-on: ${{ matrix.os }}

    steps:
      - name: ⬇️ Checkout code
        uses: actions/checkout@v4

      - name: 🧪 Unit Test ( Linux/macOS )
        # Uses -lssl -lcrypto -lpthread flags
        if: runner.os != 'Windows'
        run: |
          echo "Running Unix-like Unit Test build..." ; cd ./test
          g++ -o main main.cpp -I../include -lpthread ; ./main

      - name: 🧪 Unit Test ( Windows - Mingw )
        if: runner.os == 'Windows' && ( matrix.compiler == 'g++' || matrix.compiler == 'mingw' )
        run: |
          echo "Running Windows Unit Test (MingW) build..." ; cd ./test
          g++ -o main main.cpp -I../include -lws2_32; ./main.exe

      - name: 🧪 Unit Test ( Windows - MSVC )
        if: runner.os == 'Windows' && matrix.compiler == 'msvc'
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64
        run: |
          echo "Running Windows Unit Test (MSVC) build..."
          cd ./test
          cl /EHsc /o main.exe main.cpp /I../include ws2_32.lib
          ./main.exe

      # --- End of the workflow ---
